config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'cocktails', to: 'cocktails#index', as: :cocktails
  # get 'cocktails/new', to: 'cocktails#new'
  # post 'cocktails', to: 'cocktails#create'
  # get 'cocktails/:id', to: 'cocktails#show', as: :cocktail
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true
  validates :name, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_coctail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @dose = Dose.new
  end

  def edit
  end

  def update
    @cocktail.update(cocktail_params)
    redirect_to cocktails_path
  end

  def destroy
    @cocktail.destroy
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end

  def set_coctail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/_form.html.erb
<div class="simple-form-style">
  <%= simple_form_for(@cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
  <% end %>
</div>

app/views/cocktails/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back to list', cocktails_path %>

app/views/cocktails/index.html.erb
<h1 class="white-centered-title">List of cocktails</h1>
<div class="flex-container">
  <% @cocktails.each do |cocktail| %>
    <div class="card-product">
      <%= cl_image_tag cocktail.photo %>
      <div class="card-product-infos">
        <h2><%= cocktail.name %></h2>
        <p><%= cocktail.description %></p>
        <p><%= link_to 'show', cocktail_path(cocktail) %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="form-new-cocktail">
  <%= render 'form' %>
  <%= link_to 'Back to list', cocktails_path %>
</div>

app/views/cocktails/show.html.erb
<div class="flex-container">
  <div class="left-block-container">
    <div class="image-cocktail" >
      <%= cl_image_tag @cocktail.photo %>

    </div>
    <div class="description-container">
      <p style="color: white"><%= @cocktail.description %></p>
      <a class="btn btn-ghost" href="<%= edit_cocktail_path %>">Edit</a>
      <p><%= link_to 'Edit', edit_cocktail_path %></p>
    </div>
  </div>
  <div class="right-block-container">
    <h2><%= @cocktail.name %></h2>
    <ul class="list-inline">
      <li><i class="fas fa-star"></i></li>
      <li><i class="fas fa-star"></i></li>
      <li><i class="fas fa-star"></i></li>
      <li><i class="fas fa-star"></i></li>
      <li><i class="fas fa-star"></i></li>
    </ul>
    <% @cocktail.doses.each do |dose| %>
  <div class="right-ingredients-container">
    <div class="ingredients">
      <li>
        <%= dose.description %> <%= dose.ingredient.name %>
        <%= link_to 'Delete', dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
      </li>
      <% end %>
    </div>
    <%= render 'doses/new', cocktail: @cocktail, dose: @dose %>
  </div>
  </div>
</div>
<a class="btn btn-ghost" href="<%= cocktails_path %>">Back to list</a>

app/views/doses/_form.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit 'Add dose', class: "btn btn-primary" %>
<% end %>

app/views/doses/_new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit 'Add dose', class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dqh0reqn3/image/upload/v1565968316/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Add cocktail", "cocktails/new", class: "btn btn-ghost" %>
      </li>
    </ul>
  </div>
</div>